### ISSUE TITLE
Typo: "Visiblity"

### ISSUE THREAD

**Issue by noncombatant** [w3c/webappsec-uisecurity#5]
Should be "visibility". This typo occurs in many places.

**Comment by noncombatant** [comment]
Additional typos:

"as the Visibility Observer API. It’s goal is to allow protection to be retrofitted to legacy applications"

--> should be "its goal" (no apostrophe)
--> also, standardize on "VisibilityObserver" or "Visibility Observer" (space)

**Comment by noncombatant** [comment]
"The current specification adds the goals of prevent clickjacking and other UI redressing attacks "
--> "of preventing"

**Comment by noncombatant** [comment]
"intrepretation of policies might differ among user agents. (e.g. a tolerance hint may appy strictly to rectangular clipping in one implementation but to pixel or sub-pixel comparisons in another)"
--> "intrepretation of policies might differ among user agents. For example, a tolerance hint may apply strictly to rectangular clipping in one implementation but to pixel or sub-pixel comparisons in another."

(Typos, capitalization, and punctuation)

**Comment by noncombatant** [comment]
"boundingClienRect" --> "boundingClientRect"

**Comment by noncombatant** [comment]
"List of threshold(s) at which to trigger callback. callback will be invoked when visibleBounds' area changes from greater than or equal to any threshold to less than that threshold, and vice versa."
--> Code/variable name formatting

**Comment by noncombatant** [comment]
Conciseness generally. E.g. "There may exist considerable variability in the implementations and strategies employed by different user agents" could be simply "UA implementations may vary widely."

**Comment by hillbrad** [comment]
https://github.com/w3c/webappsec-uisecurity/pull/6
